In [1]:
from sklearn import tree
import numpy as np
import pandas as pd

In [2]:
dataset = pd.read_csv("dataset.csv")

In [3]:
dataset.head()

User ID  Gender  Age  EstimatedSalary  Purchased
0  15624510    Male   19            19000          0
1  15810944    Male   35            20000          0
2  15668575  Female   26            43000          0
3  15603246  Female   27            57000          0
4  15804002    Male   19            76000          0

In [4]:
dataset['Gender'] = pd.factorize(dataset.Gender)[0]

In [5]:
dataset.tail()

User ID  Gender  Age  EstimatedSalary  Purchased
395  15691863       1   46            41000          1
396  15706071       0   51            23000          1
397  15654296       1   50            20000          1
398  15755018       0   36            33000          0
399  15594041       1   49            36000          1

In [6]:
dataset = dataset.to_numpy()

In [7]:
print(dataset)

[[15624510        0       19    19000        0]
 [15810944        0       35    20000        0]
 [15668575        1       26    43000        0]
 ...
 [15654296        1       50    20000        1]
 [15755018        0       36    33000        0]
 [15594041        1       49    36000        1]]


In [8]:
dataTraining = np.concatenate((dataset[0:160, :], dataset[200:360, :]), axis=0)
dataTesting = np.concatenate((dataset[160:200, :], dataset[360:400, :]), axis=0)

In [9]:
print(dataTraining)
len(dataTraining)

[[15624510        0       19    19000        0]
 [15810944        0       35    20000        0]
 [15668575        1       26    43000        0]
 ...
 [15671387        1       41    72000        0]
 [15573926        0       40    71000        1]
 [15709183        0       42    54000        0]]


320

In [10]:
print(dataTesting)
len(dataTesting)

[[15744279        0       32   100000        1]
 [15670619        0       25    90000        0]
 [15599533        1       37    33000        0]
 [15757837        0       35    38000        0]
 [15697574        1       33    69000        0]
 [15578738        1       18    86000        0]
 [15762228        1       22    55000        0]
 [15614827        1       35    71000        0]
 [15789815        0       29   148000        1]
 [15579781        1       29    47000        0]
 [15587013        0       21    88000        0]
 [15570932        0       34   115000        0]
 [15794661        1       26   118000        0]
 [15581654        1       34    43000        0]
 [15644296        1       34    72000        0]
 [15614420        1       23    28000        0]
 [15609653        1       35    47000        0]
 [15594577        0       25    22000        0]
 [15584114        0       24    23000        0]
 [15673367        1       31    34000        0]
 [15685576        0       26    16000   

80

In [11]:
inputTraining = dataTraining[:,0:4]
inputTesting = dataTesting[:,0:4]
labelTraining = dataTraining[:,4]
labelTesting = dataTesting[:,4]
print(labelTraining)
len(labelTraining)

[0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 0 0 0 1 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 1 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 1 0
 0 0 0 0 0 0 0 0 0 0 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 0 0 1 0 0 0 1 0 1 1 1 0
 0 1 1 0 1 1 0 1 1 0 1 0 0 0 1 1 0 1 1 0 1 0 1 0 1 0 0 1 1 0 1 0 0 1 1 0 1
 1 0 1 1 0 0 1 0 0 1 1 1 1 1 0 1 1 1 1 0 1 1 0 1 0 1 0 1 1 1 1 0 0 0 1 1 0
 1 1 1 1 1 0 0 0 1 1 0 0 1 0 1 0 1 1 0 1 0 1 1 0 1 1 0 0 0 1 1 0 1 0 0 1 0
 1 0 0 1 1 0 0 1 1 0 1 1 0 0 1 0 1 0 1 1 1 0 1 0]


320

In [12]:
model = tree.DecisionTreeClassifier()

In [13]:
model =  model.fit(inputTraining, labelTraining)

In [14]:
hasilPrediksi = model.predict(inputTesting)
print("Label Sebenarnya : ", labelTesting)
print("Hasil Prediksi : ", hasilPrediksi)

Label Sebenarnya :  [1 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 0 1 1 1 1 0 1 1 1 0 1 0 1 0 0 1 1 0 1 1 1 1 1 1 0 1 1 1 1 1 1
 0 1 1 1 0 1]
Hasil Prediksi :  [1 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 1 1 1 0 1 1 0 0 0 1 0 1 0 1 0 1 1 0 0 1 0 1 1 1 1 1 1 0 1 1 1 1 0 0
 0 1 1 1 0 1]


In [15]:
prediksiBenar = (hasilPrediksi == labelTesting).sum()
prediksiSalah = (hasilPrediksi != labelTesting).sum()
print("Prediksi Benar : ", prediksiBenar, " Data")
print("Prediksi Salah : ", prediksiSalah, " Data")
print("Akurasi : ", prediksiBenar/(prediksiBenar+prediksiSalah) * 100, "%")

Prediksi Benar :  71  Data
Prediksi Salah :  9  Data
Akurasi :  88.75 %
