In [23]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
dataset = pd.read_csv('tahun-2021-jumlah-penduduk-berdasarkan-kelompok-umur-bandung.csv')
X = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [25]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [26]:
from sklearn.impute import SimpleImputer

imputer = SimpleImputer(missing_values=np.nan, strategy='constant')
imputer.fit(X[:, 1:3])
X[:, 1:3] = imputer.transform(X[:, 1:3])

In [27]:
dataset

Kecamatan       Kelurahan  Usia 0-4 Thn  Usia 5-9 Thn  Usia 10-14 Thn  \
0           Andir         Campaka          1249          1499            1608   
1           Andir         Ciroyom          1471          1835            1835   
2           Andir  Dungus Cariang          1288          1500            1578   
3           Andir          Garuda           690           832             830   
4           Andir     Kebon Jeruk           599           811             780   
..            ...             ...           ...           ...             ...   
146  Ujung Berung       Cigending          1207          1408            1493   
147  Ujung Berung    Pasanggrahan          1562          1867            1810   
148  Ujung Berung     Pasir Endah          1245          1481            1405   
149  Ujung Berung      Pasirwangi          1430          1637            1573   
150  Ujung Berung       Pasirjati          1293          1625            1606   

     Usian 15-19 Thn  Usia 20-24 Thn  Usia 25-29 Thn  Usia 30-34 Thn  \
0               1509            1499            1493            1293   
1               1609            1597            1556            1408   
2               1469            1497            1473            1280   
3                824             796             790             755   
4                812             847             781             744   
..               ...             ...             ...             ...   
146             1384            1347            1331            1189   
147             1669            1712            1677            1555   
148             1330            1277            1379            1284   
149             1361            1297            1453            1300   
150             1477            1454            1374            1277   

     Usia 35-39 Thn  Usia 40-44 Thn  Usia 45-49 Thn  Usia 50-54 Thn  \
0              1465            1514            1414            1237   
1              1589            1641            1316            1160   
2              1443            1492            1464            1252   
3               831             891             813             754   
4               863             959             807             832   
..              ...             ...             ...             ...   
146            1313            1324            1210            1054   
147            1623            1525            1496            1295   
148            1407            1338            1152            1081   
149            1476            1362            1220            1008   
150            1436            1460            1300            1073   

     Usia 55-59 Thn  Usia 60-64 Thn  Usia 65-69 Thn  Usia 70-74 Thn  \
0               932             734             484             246   
1               975             762             548             292   
2              1011             788             583             349   
3               553             451             336             199   
4               707             626             508             365   
..              ...             ...             ...             ...   
146             916             722             492             247   
147             957             667             447             274   
148             835             733             507             276   
149             724             537             348             185   
150             807             569             410             178   

     Usia > 75 Thn  
0              317  
1              397  
2              410  
3              272  
4              514  
..             ...  
146            257  
147            330  
148            272  
149            202  
150            228  

[151 rows x 18 columns]

In [28]:
print(X)

[['Andir' 'Campaka' 1249 ... 734 484 246]
 ['Andir' 'Ciroyom' 1471 ... 762 548 292]
 ['Andir' 'Dungus Cariang' 1288 ... 788 583 349]
 ...
 ['Ujung Berung' 'Pasir Endah' 1245 ... 733 507 276]
 ['Ujung Berung' 'Pasirwangi' 1430 ... 537 348 185]
 ['Ujung Berung' 'Pasirjati' 1293 ... 569 410 178]]


In [29]:
print(y)

[317 397 410 272 514 477 434 139 361 228 194 266 370 424 481 363 336 298
 200 370 374 425 144 306 145 525 458 284 188  97 162 285 157 133 123 444
 249 306 272 163 576 292 404 479 295 222 280 299 239 296 417 567 484 299
 108 101 127 522 155 452 445 154 712 422 658 331 264 459 324 629 358 388
 290 329 191 263 197 283 502 280 450 359 384 402 464 499 263  86  93 105
  69 274 792 345 102 565 643  35 434 103  43 638 295 295 293 280 442 311
 391 230 294 322 241 707 365 229 180 230  63  48 166 183 373 246 711 249
 394 306 310 409 346 275 298 478 505 502 391 328 694 279 781 306 206 220
 321 264 257 330 272 202 228]


In [30]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(sparse=False), [0, 1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [31]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 151 entries, 0 to 150
Data columns (total 18 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   Kecamatan        151 non-null    object
 1   Kelurahan        151 non-null    object
 2   Usia 0-4 Thn     151 non-null    int64 
 3   Usia 5-9 Thn     151 non-null    int64 
 4   Usia 10-14 Thn   151 non-null    int64 
 5   Usian 15-19 Thn  151 non-null    int64 
 6   Usia 20-24 Thn   151 non-null    int64 
 7   Usia 25-29 Thn   151 non-null    int64 
 8   Usia 30-34 Thn   151 non-null    int64 
 9   Usia 35-39 Thn   151 non-null    int64 
 10  Usia 40-44 Thn   151 non-null    int64 
 11  Usia 45-49 Thn   151 non-null    int64 
 12  Usia 50-54 Thn   151 non-null    int64 
 13  Usia 55-59 Thn   151 non-null    int64 
 14  Usia 60-64 Thn   151 non-null    int64 
 15  Usia 65-69 Thn   151 non-null    int64 
 16  Usia 70-74 Thn   151 non-null    int64 
 17  Usia > 75 Thn    151 non-null    in

In [32]:
print(X)

[[1.0 0.0 0.0 ... 734 484 246]
 [1.0 0.0 0.0 ... 762 548 292]
 [1.0 0.0 0.0 ... 788 583 349]
 ...
 [0.0 0.0 0.0 ... 733 507 276]
 [0.0 0.0 0.0 ... 537 348 185]
 [0.0 0.0 0.0 ... 569 410 178]]


In [33]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [34]:
print(y)

[ 66  89  93  47 115 107  98  16  79  36  29  46  82  96 110  80  74  61
  31  82  84  97  17  63  18 117 104  53  27   7  22  54  21  15  13 100
  42  63  47  23 120  56  91 109  59  35  51  62  39  60  94 119 111  62
  12   8  14 116  20 103 101  19 128  95 124  73  45 105  69 121  77  86
  55  71  28  44  30  52 113  51 102  78  85  90 106 112  44   5   6  11
   4  48 130  75   9 118 123   0  98  10   1 122  59  59  57  51  99  65
  87  38  58  68  40 126  81  37  25  38   3   2  24  26  83  41 127  42
  88  63  64  92  76  49  61 108 114 113  87  70 125  50 129  63  33  34
  67  45  43  72  47  32  36]


In [35]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [36]:
print(X_train)

[[0.0 0.0 0.0 ... 924 672 376]
 [0.0 0.0 0.0 ... 1019 678 442]
 [0.0 0.0 0.0 ... 334 271 196]
 ...
 [0.0 0.0 0.0 ... 558 405 200]
 [0.0 0.0 0.0 ... 1143 869 631]
 [0.0 0.0 0.0 ... 748 472 288]]


In [37]:
print(X_test)

[[0.0 0.0 0.0 ... 648 559 398]
 [0.0 0.0 0.0 ... 969 650 327]
 [0.0 0.0 0.0 ... 809 521 234]
 ...
 [0.0 0.0 0.0 ... 1027 665 276]
 [0.0 0.0 0.0 ... 667 447 274]
 [0.0 0.0 0.0 ... 498 362 226]]


In [38]:
print(y_train)

[113 121  64  81  39  62  27  12  87  40  61   2  59  20   3  31 115  35
 103  23  42  38  50  65  61  88 112  83 118  46 126  41  82  93  57  98
  63  58  73   8  45 125  51 128  28  25  75   1  11  29  13  21 127  47
  90  68  36  53  63 105  36  76   0  51  43   5  32  38 124  80  85  56
 102 111 104  30 109  18  87  26  34  60  97  77  47  33  22  47  99  62
  37  96   6  79  78 101  66  89 116  17  19  95  16  44 123  69  94 122
  84 117 114  86  92  67  51 108  70  55 129  63]


In [39]:
print(y_test)

[110  98  44  74  49  14  63  59   7  24   9 107  59 119 113  91 130  45
  54 100   4 106  52 120  42  10  15  82  71  72  48]


In [40]:
from sklearn.preprocessing import StandardScaler as SS
sc = SS()
X_train[:, -1:] = sc.fit_transform(X_train[:, -1:])
X_test[:, -1:] = sc.transform(X_test[:, -1:])

In [41]:
print(X)

[[1.0 0.0 0.0 ... 734 484 246]
 [1.0 0.0 0.0 ... 762 548 292]
 [1.0 0.0 0.0 ... 788 583 349]
 ...
 [0.0 0.0 0.0 ... 733 507 276]
 [0.0 0.0 0.0 ... 537 348 185]
 [0.0 0.0 0.0 ... 569 410 178]]


In [42]:
print(X_test)

[[0.0 0.0 0.0 ... 648 559 1.0251472691326815]
 [0.0 0.0 0.0 ... 969 650 0.46999219807119]
 [0.0 0.0 0.0 ... 809 521 -0.2571827541642847]
 ...
 [0.0 0.0 0.0 ... 1027 665 0.07121883716786516]
 [0.0 0.0 0.0 ... 667 447 0.0555806661520485]
 [0.0 0.0 0.0 ... 498 362 -0.31973543822755135]]
